### ISSUE TITLE
Not equipping anything

### ISSUE THREAD

**Issue by tjesp** [AlexFolland/AutoGear#65] opened 2024-06-13 07:40 UTC
I just did an "/ag scan" and as shown there were two upgrades:

https://imgur.com/arzF8MW

However none of them were equipped. This is cataclysm classic.

If I load pawn and select to override scale with feral everying equips fine.

**Comment by AlexFolland** [comment] 2024-06-13 07:46
Thanks for the report.  I can't reproduce this here, so please enable `/ag debuginfo` and then show me screenshots of the following:

1. your AutoGear options menu
2. the tooltips for all 4 of those items

Doing this will help me investigate what AutoGear might be doing that I haven't seen before.

FYI, you can paste images (like cropped screenshots) directly from your clipboard into GitHub messages for convenience.  You don't have to paste a link from imgur.

**Comment by AlexFolland** [comment] 2024-06-18 11:25
I still can't reproduce this.  I tried disabling Pawn evaluation and disabling a scale override, and I didn't see the issue.  The upgrades I removed from my character were equipped.  Are you still able to reproduce this?

**Comment by AlexFolland** [comment] 2024-06-18 19:19
I reproduced an issue that was like this.  Quest rewards in my quest log that I didn't actually have were being considered best currently-available items, which was causing AutoGear to try to equip them and failing.  I've resolved that issue now and pushed the change to the `master` branch.  Can you please test it there and confirm those items were quest rewards in the quest log?

**Comment by AlexFolland** [comment] 2024-06-24 22:01
I think this is resolved, so I'm closing the ticket now.  Please let me know if you can still reproduce this and I'll reopen the ticket.  Thanks for your report.

**Comment by tjesp** [comment] 2024-06-30 00:27
I got it again on a warrior below level 10 (spec none)

AG Config:
https://imgur.com/a/kyXwnJb

Spec (below level 10):
https://imgur.com/a/fy2ZumU

Tooltip with debuginfo:
https://imgur.com/a/04w7oEz

**Comment by prot3ct** [comment] 2024-06-30 11:47
I am getting this as wel on SoD Era. In chat In the chat logs say items are being equiped, but they are not.

**Comment by AlexFolland** [comment] 2024-07-01 00:03
Are these items you actually have?  Is it happening outside combat?  Can I get more details?  I haven't seen this yet, so the more details I can get, the better.  I need to know how it can happen to be able to understand why it's happening to some people and not me.

**Comment by AlexFolland** [comment] 2024-07-01 08:43
I just ran 4 dungeons and quested for 2 hours, got multiple upgrades from both quests and automatic loot rolls, and never encountered this issue.  How can I reproduce it?  Under what circumstances are you seeing it?

**Comment by AlexFolland** [comment] 2024-07-03 03:03
Are either of you able to reproduce this issue again and then `/dump AutoGearBestItems[INVSLOT_TRINKET1]` and copy the text output with a chat addon like Prat that lets you copy-paste from the chat? Also `/dump AutoGearEquippedItems[INVSLOT_TRINKET1]` and `/dump AutoGearActionQueue` might tell me something.

**Comment by tjesp** [comment] 2024-07-04 01:30
https://imgur.com/a/JnHVXna

Nothing was equipped. Of course I first saw you message after and now it works. It doesn't work sporadically.

**Comment by tjesp** [comment] 2024-07-11 07:20
Got it. I can add that I did not roll on gear in a dungeon either:

`[09:16:07] Dump: value=AutoGearBestItems[10]
[09:16:07] [1]={
[09:16:07]   info={
[09:16:07]     Intellect=9,
[09:16:07]     isGear=true,
[09:16:07]     shouldShowScoreInTooltip=1,
[09:16:07]     Haste=9,
[09:16:07]     bop=1,
[09:16:07]     item={
[09:16:07]       GetItemLocation=<function>,
[09:16:07]       SetItemLink=<function>,
[09:16:07]       HasItemLocation=<function>,
[09:16:07]       LockItem=<function>,
[09:16:07]       itemLocation={
[09:16:07]         Clear=<function>,
[09:16:07]         IsEquipmentSlot=<function>,
[09:16:07]         IsEqualToBagAndSlot=<function>,
[09:16:07]         equipmentSlotIndex=10,
[09:16:07]         SetBagAndSlot=<function>,
[09:16:07]         IsBagAndSlot=<function>,
[09:16:07]         SetEquipmentSlot=<function>,
[09:16:07]         HasAnyLocation=<function>,
[09:16:07]         GetEquipmentSlot=<function>,
[09:16:07]         IsEqualToEquipmentSlot=<function>,
[09:16:07]         IsEqualTo=<function>,
[09:16:07]         GetBagAndSlot=<function>
[09:16:07]       },
[09:16:07]       GetItemID=<function>,
[09:16:07]       IsItemDataCached=<function>,
[09:16:07]       GetInventoryTypeName=<function>,
[09:16:07]       GetCurrentItemLevel=<function>,
[09:16:07]       GetItemQualityColor=<function>,
[09:16:07]       UnlockItem=<function>,
[09:16:07]       Clear=<function>,
[09:16:07]       GetItemIcon=<function>,
[09:16:07]       ContinueOnItemLoad=<function>,
[09:16:07]       ContinueWithCancelOnItemLoad=<function>,
[09:16:07]       SetItemLocation=<function>,
[09:16:07]       IsItemLocked=<function>,
[09:16:07]       IsItemInPlayersControl=<function>,
[09:16:07]       IsDataEvictable=<function>,
[09:16:07]       GetItemGUID=<function>,
[09:16:07]       GetInventoryType=<function>,
[09:16:07]       IsItemEmpty=<function>,
[09:16:07]       GetStaticBackingItem=<function>,
[09:16:07]       SetItemID=<function>,
[09:16:07]       GetItemQuality=<function>,
[09:16:07]       GetItemName=<function>,
[09:16:07]       GetItemLink=<function>
[09:16:07]     },
[09:16:07]     Armor=73,
[09:16:07]     equipped=true,
[09:16:07]     validGearSlots={
[09:16:07]       [1]=10
[09:16:07]     },
[09:16:07]     invType=10,
[09:16:07]     link="|[Gloves of Shadowy Mist]|",
[09:16:07]     rarityColor={
[09:16:07]       hex="|",
[09:16:07]       r=0,
[09:16:07]       color={
[09:16:07]         a=1,
[09:16:07]         b=0.8666667342186,
[09:16:07]         g=0.43921571969986,
[09:16:07]         GetRGBA=<function>,
[09:16:07]         IsRGBEqualTo=<function>,
[09:16:07]         SetRGB=<function>,
[09:16:07]         GetRGB=<function>,
[09:16:07]         r=0,
[09:16:07]         GenerateHexColorMarkup=<function>,
[09:16:07]         WrapTextInColorCode=<function>,
[09:16:07]         GenerateHexColor=<function>,
[09:16:07]         IsEqualTo=<function>,
[09:16:07]         OnLoad=<function>,
[09:16:07]         GenerateHexColorNoAlpha=<function>,
[09:16:07]         SetRGBA=<function>,
[09:16:07]         GetRGBAsBytes=<function>,
[09:16:07]         GetRGBAAsBytes=<function>
[09:16:07]       },
[09:16:07]       g=0.43921571969986,
[09:16:07]       b=0.8666667342186
[09:16:07]     },
[09:16:07]     numValidGearSlots=1,
[09:16:07]     classID=4,
[09:16:07]     id=18306,
[09:16:07]     name="Gloves of Shadowy Mist",
[09:16:07]     subclassID=1,
[09:16:07]     Stamina=9,
[09:16:07]     usable=1,
[09:16:07]     rarity=3,
[09:16:07]     guid="Item-4453-0-40000005311C9948"
[09:16:07]   },
[09:16:07]   score=14.923,
[09:16:07]   equipped=1
[09:16:07] `

`[09:17:43] Dump: value=AutoGearEquippedItems[10]
[09:17:43] [1]={
[09:17:43]   equipped=1,
[09:17:43]   score=14.923,
[09:17:43]   info={
[09:17:43]     Intellect=9,
[09:17:43]     isGear=true,
[09:17:43]     guid="Item-4453-0-40000005311C9948",
[09:17:43]     Haste=9,
[09:17:43]     bop=1,
[09:17:43]     item={
[09:17:43]       GetItemLocation=<function>,
[09:17:43]       SetItemLink=<function>,
[09:17:43]       HasItemLocation=<function>,
[09:17:43]       LockItem=<function>,
[09:17:43]       itemLocation={
[09:17:43]         Clear=<function>,
[09:17:43]         IsEquipmentSlot=<function>,
[09:17:43]         IsEqualToBagAndSlot=<function>,
[09:17:43]         equipmentSlotIndex=10,
[09:17:43]         SetBagAndSlot=<function>,
[09:17:43]         IsBagAndSlot=<function>,
[09:17:43]         SetEquipmentSlot=<function>,
[09:17:43]         HasAnyLocation=<function>,
[09:17:43]         GetEquipmentSlot=<function>,
[09:17:43]         IsEqualToEquipmentSlot=<function>,
[09:17:43]         GetBagAndSlot=<function>,
[09:17:43]         IsEqualTo=<function>
[09:17:43]       },
[09:17:43]       GetItemID=<function>,
[09:17:43]       IsItemDataCached=<function>,
[09:17:43]       GetInventoryTypeName=<function>,
[09:17:43]       GetCurrentItemLevel=<function>,
[09:17:43]       GetItemQualityColor=<function>,
[09:17:43]       UnlockItem=<function>,
[09:17:43]       Clear=<function>,
[09:17:43]       GetItemIcon=<function>,
[09:17:43]       IsItemLocked=<function>,
[09:17:43]       GetItemLink=<function>,
[09:17:43]       SetItemLocation=<function>,
[09:17:43]       GetItemName=<function>,
[09:17:43]       IsItemInPlayersControl=<function>,
[09:17:43]       GetItemQuality=<function>,
[09:17:43]       GetItemGUID=<function>,
[09:17:43]       GetInventoryType=<function>,
[09:17:43]       IsItemEmpty=<function>,
[09:17:43]       GetStaticBackingItem=<function>,
[09:17:43]       SetItemID=<function>,
[09:17:43]       IsDataEvictable=<function>,
[09:17:43]       ContinueWithCancelOnItemLoad=<function>,
[09:17:43]       ContinueOnItemLoad=<function>
[09:17:43]     },
[09:17:43]     Armor=73,
[09:17:43]     equipped=true,
[09:17:43]     usable=1,
[09:17:43]     validGearSlots={
[09:17:43]       [1]=10
[09:17:43]     },
[09:17:43]     invType=10,
[09:17:43]     link="|[Gloves of Shadowy Mist]|",
[09:17:43]     rarityColor={
[09:17:43]       hex="|",
[09:17:43]       r=0,
[09:17:43]       color={
[09:17:43]         a=1,
[09:17:43]         b=0.8666667342186,
[09:17:43]         g=0.43921571969986,
[09:17:43]         GetRGBA=<function>,
[09:17:43]         IsRGBEqualTo=<function>,
[09:17:43]         SetRGB=<function>,
[09:17:43]         GetRGB=<function>,
[09:17:43]         r=0,
[09:17:43]         GenerateHexColorMarkup=<function>,
[09:17:43]         WrapTextInColorCode=<function>,
[09:17:43]         GenerateHexColor=<function>,
[09:17:43]         IsEqualTo=<function>,
[09:17:43]         OnLoad=<function>,
[09:17:43]         GenerateHexColorNoAlpha=<function>,
[09:17:43]         SetRGBA=<function>,
[09:17:43]         GetRGBAsBytes=<function>,
[09:17:43]         GetRGBAAsBytes=<function>
[09:17:43]       },
[09:17:43]       g=0.43921571969986,
[09:17:43]       b=0.8666667342186
[09:17:43]     },
[09:17:43]     numValidGearSlots=1,
[09:17:43]     classID=4,
[09:17:43]     shouldShowScoreInTooltip=1,
[09:17:43]     Stamina=9,
[09:17:43]     name="Gloves of Shadowy Mist",
[09:17:43]     rarity=3,
[09:17:43]     subclassID=1,
[09:17:43]     id=18306
[09:17:43]   }
[09:17:43] }`

The buffer in prat was not quite large enough for /dump AutoGearActionQueue but here is what I could get:

`[09:19:03]         SetItemID=<function>,
[09:19:03]         IsDataEvictable=<function>,
[09:19:03]         ContinueWithCancelOnItemLoad=<function>,
[09:19:03]         ContinueOnItemLoad=<function>
[09:19:03]       },
[09:19:03]       usable=1,
[09:19:03]       Spirit=7,
[09:19:03]       shouldShowScoreInTooltip=1,
[09:19:03]       validGearSlots={
[09:19:03]         [1]=11,
[09:19:03]         [2]=12
[09:19:03]       },
[09:19:03]       invType=11,
[09:19:03]       link="|[Tumultuous Ring of the Moon]|",
[09:19:03]       rarityColor={
[09:19:03]         hex="|",
[09:19:03]         r=0,
[09:19:03]         color={
[09:19:03]           a=1,
[09:19:03]           b=0.8666667342186,
[09:19:03]           g=0.43921571969986,
[09:19:03]           GetRGBA=<function>,
[09:19:03]           IsRGBEqualTo=<function>,
[09:19:03]           SetRGB=<function>,
[09:19:03]           GetRGB=<function>,
[09:19:03]           r=0,
[09:19:03]           GenerateHexColorMarkup=<function>,
[09:19:03]           WrapTextInColorCode=<function>,
[09:19:03]           GenerateHexColor=<function>,
[09:19:03]           IsEqualTo=<function>,
[09:19:03]           OnLoad=<function>,
[09:19:03]           GenerateHexColorNoAlpha=<function>,
[09:19:03]           SetRGBA=<function>,
[09:19:03]           GetRGBAsBytes=<function>,
[09:19:03]           GetRGBAAsBytes=<function>
[09:19:03]         },
[09:19:03]         g=0.43921571969986,
[09:19:03]         b=0.8666667342186
[09:19:03]       },
[09:19:03]       numValidGearSlots=2,
[09:19:03]       classID=4,
[09:19:03]       equipped=false,
[09:19:03]       Stamina=4,
[09:19:03]       name="Tumultuous Ring of the Moon",
[09:19:03]       rarity=3,
[09:19:03]       subclassID=0,
[09:19:03]       id=51992
[09:19:03]     },
[09:19:03]     container=0
[09:19:03]   },
[09:19:03]   [3]={
[09:19:03]     replaceSlot=16,
[09:19:03]     action="equip",
[09:19:03]     slot=9,
[09:19:03]     score=12.172,
[09:19:03]     t=97720.998,
[09:19:03]     info={
[09:19:03]       Intellect=7,
[09:19:03]       isGear=true,
[09:19:03]       guid="Item-4453-0-40000005311F3C8C",
[09:19:03]       bop=1,
[09:19:03]       is1hWeaponOrOffHand=1,
[09:19:03]       item={
[09:19:03]         GetItemLocation=<function value>,
[09:19:03]         SetItemLink=<function value>,
[09:19:03]         HasItemLocation=<function value>,
[09:19:03]         LockItem=<function value>,
[09:19:03]         itemLocation={
[09:19:03]           Clear=<function value>,
[09:19:03]           IsEquipmentSlot=<function value>,
[09:19:03]           IsEqualToBagAndSlot=<function value>,
[09:19:03]           SetBagAndSlot=<function value>,
[09:19:03]           IsBagAndSlot=<function value>,
[09:19:03]           SetEquipmentSlot=<function value>,
[09:19:03]           HasAnyLocation=<function value>,
[09:19:03]           slotIndex=9,
[09:19:03]           GetEquipmentSlot=<function value>,
[09:19:03]           IsEqualToEquipmentSlot=<function value>,
[09:19:03]           bagID=0,
[09:19:03]           GetBagAndSlot=<function value>,
[09:19:03]           IsEqualTo=<function value>
[09:19:03]         },
[09:19:03]         GetItemID=<function value>,
[09:19:03]         IsItemDataCached=<function value>,
[09:19:03]         GetInventoryTypeName=<function value>,
[09:19:03]         GetCurrentItemLevel=<function value>,
[09:19:03]         GetItemQualityColor=<function value>,
[09:19:03]         UnlockItem=<function value>,
[09:19:03]         Clear=<function value>,
[09:19:03]         GetItemIcon=<function value>,
[09:19:03]         IsItemLocked=<function value>,
[09:19:03]         GetItemLink=<function value>,
[09:19:03]         SetItemLocation=<function value>,
[09:19:03]         GetItemName=<function value>,
[09:19:03]         IsItemInPlayersControl=<function value>,
[09:19:03]         GetItemQuality=<function value>,
[09:19:03]         GetItemGUID=<function value>,
[09:19:03]         GetInventoryType=<function value>,
[09:19:03]         IsItemEmpty=<function value>,
[09:19:03]         GetStaticBackingItem=<function value>,
[09:19:03]         SetItemID=<function value>,
[09:19:03]         IsDataEvictable=<function value>,
[09:19:03]         ContinueWithCancelOnItemLoad=<function value>,
[09:19:03]         ContinueOnItemLoad=<function value>
[09:19:03]       },
[09:19:03]       usable=1,
[09:19:03]       shouldShowScoreInTooltip=1,
[09:19:03]       equipped=false,
[09:19:03]       Spirit=7,
[09:19:03]       rarity=3,
[09:19:03]       validGearSlots={
[09:19:03]         [1]=16
[09:19:03]       },
[09:19:03]       invType=21,
[09:19:03]       link="|[Hand of Righteousness]|",
[09:19:03]       rarityColor=AutoGearActionQueue[2].info.rarityColor,
[09:19:03]       numValidGearSlots=1,
[09:19:03]       classID=2,
[09:19:03]       Damage=73.5,
[09:19:03]       isWeaponOrOffHand=1,
[09:19:03]       name="Hand of Righteousness",
[09:19:03]       DPS=27.2,
[09:19:03]       subclassID=4,
[09:19:03]       id=7721
[09:19:03]     },
[09:19:03]     container=0
[09:19:03]   }
[09:19:03] }`

**Comment by tjesp** [comment] 2024-07-11 07:29
I can add that reloading doesn't fix it in my case now.

**Comment by tjesp** [comment] 2024-07-11 08:49
Alright I can add something more. I have been running a lot of dungeons today. Autogear did not roll on gear. After I left dungeon and was standing in Stormwind suddenly my chat was spammed with rolls from autogear. Of course I had already left the dungeon.

**Comment by AlexFolland** [comment] 2024-07-25 16:40
I've made a change that may resolve this issue in the latest untagged commits.  Does that fix it for you?

**Comment by AlexFolland** [comment] 2024-11-27 01:34
I've updated AutoGear to work for DF and TWW.  There are 3 known issues:

- Typing `/ag` to show the options menu does something weird and doesn't show the addon options menu properly.  It shows the main settings menu instead.  I'm not sure why right now.
- Tooltips in the options menu don't show up at all, so it's hard to learn about the options right now.
- All AutoGear built-in stat weights are not updated, so just use Pawn scales for weights because AutoGear's built-in weights are either not ideal or don't work at all right now.

I plan to solve the options menu issues soon.

Please comment again if it's still not working for you.

**Closed by AlexFolland** 2024-11-27 01:34 UTC
