### ISSUE TITLE
Autogear dont work on wow cllassic

### ISSUE THREAD

**Issue by pyr0m4tic** [AlexFolland/AutoGear#36] opened 2022-11-08 17:31 UTC
![image](https://user-images.githubusercontent.com/117763632/200633391-10d4101f-5c96-4604-8740-0d1b3b41cb26.png)

![image](https://user-images.githubusercontent.com/117763632/200633798-d38bf2bd-cd2b-4f0e-826f-af918d32a4b2.png)

![image](https://user-images.githubusercontent.com/117763632/200633853-5524ef9a-ebef-48aa-8f72-96eb1a3dac6c.png)

I don`t now why  it doesnt work,
The wow WOLTK classic Addon works perfect.

**Comment by AlexFolland** [comment] 2022-11-08 20:17
I'd like to see any errors you may have, as that will help me determine the cause of the issue.

Please install BugSack and BugGrabber which are addons which gather error information, then reload UI and try to access the AutoGear menu again.

If there are any errors, the BugSack minimap icon will become red.  You can click on it to see errors.  If any mention AutoGear, please copy the full text from BugSack's error window and paste the full text here.

**Comment by pyr0m4tic** [comment] 2022-11-08 23:20
> I'd like to see any errors you may have, as that will help me determine the cause of the issue.
> 
> Please install BugSack and BugGrabber which are addons which gather error information, then reload UI and try to access the AutoGear menu again.
> 
> If there are any errors, the BugSack minimap icon will become red. You can click on it to see errors. If any mention AutoGear, please copy the full text from BugSack's error window and paste the full text here.

1x AutoGear\AutoGear.lua:3737: attempt to call global 'IsXPUserDisabled' (a nil value)
[string "@AutoGear\AutoGear.lua"]:3737: in function `AutoGearDetermineItemScore'
[string "@AutoGear\AutoGear.lua"]:2555: in function `AutoGearUpdateEquippedItems'
[string "@AutoGear\AutoGear.lua"]:1797: in function <AutoGear\AutoGear.lua:1790>

Locals:
info = <table> {
 validGearSlots = <table> {
 }
 invType = 4
 link = "|cffffffff|Hitem:49::::::::4:::::::::|h[Footpad's Shirt]|h|r"
 id = 49
 classID = 4
 usable = 1
 shouldShowScoreInTooltip = 1
 rarityColor = <table> {
 }
 name = "Footpad's Shirt"
 isGear = true
 rarity = 1
 subclassID = 0
 equipped = true
 item = <table> {
 }
}
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to call global 'IsXPUserDisabled' (a nil value)"
E = 0.000001
maxPlayerLevel = 60

**Comment by AlexFolland** [comment] 2022-11-11 08:13
OK, I see the problem.  I'll fix it soon.  In the mean time, I think you can comment out the line with IsUserXPDisabled in your local copy as a workaround.  That doesn't exist in vanilla.

**Comment by AlexFolland** [comment] 2022-11-12 22:55
I've just released a fix in release `2022-11-12-release`. If you're reading this immediately upon posting this response, the release isn't available yet, but it'll be available in about 10 minutes usually. When it's available, would you mind checking it?

**Comment by AlexFolland** [comment] 2022-12-06 17:49
My fix probably worked for Vanilla Classic, since it's pretty simple.  Therefore, I'm closing this.  If you comment that it's not fixed, I'll reopen it and we can try to figure it out together again.

**Closed by AlexFolland** 2022-12-06 17:49 UTC
