### ISSUE TITLE
When using "weapon and shield" one-hand weapons score arent not calcualted properly

### ISSUE THREAD

**Issue by prot3ct** [AlexFolland/AutoGear#66] opened 2024-06-16 21:55 UTC
I am using "weapon and shield" in Autogear. When I do /ag scan, score of one-hand weapons is not calculated properly, only main-hand are evaluated properly. in Cata there are barely main-hand weapons and its super annoying.

**Comment by AlexFolland** [comment] 2024-06-16 22:10
Thanks for the report. I haven't seen this and don't have a simple way to reproduce it here, so please enable `/ag debuginfo` and then show me screenshots of the following:

1. your AutoGear options menu
2. the tooltips for all relevant main hand and one hand items; especially the ones you are seeing the issue with

Doing this will help me investigate what AutoGear might be doing that I haven't seen before.

FYI, you can paste images (like cropped screenshots) directly from your clipboard into GitHub messages for convenience.

Sorry for asking for this, but I do want to help you but don't have the particular scenario you're in or enough time to create the scenario here on my end. I appreciate your help with screenshots like this tremendously.

**Comment by prot3ct** [comment] 2024-06-16 22:13
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/ae991b10-d23b-4038-8597-18bc9889c963)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/035a57c8-86b0-4945-8f84-5a8d704c80f7)

Screenshot 1 is one-hand 
Screenshot 2 is main-hand

You cann see gray main-hand has better score, which is strange.

**Comment by prot3ct** [comment] 2024-06-16 22:14
This is Protection Paladin and weapon type value in code is "weapon and shield"

**Comment by AlexFolland** [comment] 2024-06-16 22:17
Please use the latest version of AutoGear.  From your other bug report, I have seen that you are not using the latest version, from either GitHub or CurseForge.  The logic related to this report has been changed in the weeks since you've last updated.

**Comment by prot3ct** [comment] 2024-06-16 22:24
I am pretty sure downloaded the latest from master. Isn't it the same as the one in curseforge?

**Comment by prot3ct** [comment] 2024-06-16 22:31
Right before marking these screenshots I downloaded lastest master from github. I just tried again and debuginfo shows same numbers. Are you sure you pushed those changes?

**Comment by AlexFolland** [comment] 2024-06-16 23:22
Yes.  Please make sure you have extracted the addon to the correct location, or just use the release from CurseForge with an addon manager like WowUp-CF which can install addons from CurseForge in the correct directory.

**Comment by AlexFolland** [comment] 2024-06-16 23:28
Your screenshots do not have the "soulbinding" line that's been in the latest version for a while now.  You can see that line in the code here, already on GitHub: https://github.com/AlexFolland/AutoGear/blob/238f555cf2a4f35dcf8b1e5a828eab80fec5f27a/AutoGear.lua#L4371

**Comment by prot3ct** [comment] 2024-06-17 00:36
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/00910314-4a91-40a1-9deb-2d4d27d7c0ce)
![image](https://github.com/AlexFolland/AutoGear/assets/13061058/6554b427-84c8-438e-98fd-3c3799b7314b)

Here are both weapons, One handder has much lower score while stamina and strength are top score stats. I trie to find main-hand with same stats, but the score difference is quite big I assure its not cus of the different stats.

**Comment by AlexFolland** [comment] 2024-06-17 01:54
Thanks for the screenshots and furthering the report.  Although I have changed the logic in the latest version and you are still not using the latest version in these screenshots, this does look like it could be an issue in the latest version, although I'll need to investigate myself why it might be.  These items have the same item class ID and item subclass ID as each other, so they should be treated identically, but maybe they're not being.  While I investigate this and try to figure it out, please test with the latest version.

Also, please fix your screenshot methodology as suggested in the other ticket.  There is no reason to use such stretched screenshots.

**Comment by AlexFolland** [comment] 2024-06-17 01:55
Also, what are your settings?  Do you have any locked slots?

**Comment by AlexFolland** [comment] 2024-06-17 15:50
OK, I tried my best to reproduce this, but couldn't.  My protection warrior was also using "weapon and shield" weapon type along with Pawn scoring.

I can see by looking at the "Pawn value" line in your debug tooltips (which is a number that comes dirently from Pawn) that the wrong scoring comes directly from Pawn.  I expect that your stat weights are wrong in Pawn.  Please update Pawn and fix your stat weights so that it doesn't have extra weight for "one hand" items over "main hand" items.

**Comment by AlexFolland** [comment] 2024-06-17 15:51
I'm going to close this one.  It is a Pawn issue.  If you disagree, please feel free to show me your stat weights and settings and explain why.

**Closed by AlexFolland** 2024-06-17 15:51 UTC

**Comment by AlexFolland** [comment] 2024-06-18 06:44
By the way, I investigated this on my warrior just to re-confirm and I found the issue in Pawn.  See here:

![image](https://github.com/AlexFolland/AutoGear/assets/601517/8ed459e6-019d-4b42-ad83-75a4a7ef0b53)

Pawn's default tank scales right now have "main hand" weights and not "one hand" weights, so they are pretty broken.
