### ISSUE TITLE
Curseforge version release 8/30/23 giving lua error and not equipping

### ISSUE THREAD

**Issue by Aquicy** [AlexFolland/AutoGear#53] opened 2023-11-08 20:56 UTC
//it still shows reasoning behind gear swapping in chat and even says equipping, but doesnt do it. 

Message: GameTooltip:HookScript(): Doesn't have a "OnTooltipSetItem" script
Time: Wed Nov  8 14:46:10 2023
Count: 1
Stack: GameTooltip:HookScript(): Doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `?'
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:4129: in main chunk

Locals: (*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:410
 shoppingTooltips = <table> {
 }
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 HasDataInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:514
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 updateTooltipTimer = 0.200000
 SetTotem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetBuybackItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:492
 GetPrimaryTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:499
 TextRight1 = GameTooltipTextRight1 {
 }
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:1055
 SetPetAction = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:1074
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetItemKey = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:1112
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 supportsItemComparison = true
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 supportsDataRefresh = true
 SetEquipmentSet = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:1116
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:1049
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:539
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:400
 NineSli
Message: Interface/AddOns/AutoGear/AutoGear.lua:368: attempt to call global 'AutoGearMain' (a nil value)
Time: Wed Nov  8 14:47:16 2023
Count: 8517
Stack: Interface/AddOns/AutoGear/AutoGear.lua:368: attempt to call global 'AutoGearMain' (a nil value)
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:368: in function <Interface/AddOns/AutoGear/AutoGear.lua:367>

Locals: (*temporary) = nil
(*temporary) = "attempt to call global 'AutoGearMain' (a nil value)"

**Comment by Aquicy** [comment] 2023-11-08 21:05
class is ret pally on retail version 10.2.0.52068
ss of chat
https://imgur.com/a/6vwILoJ

**Comment by AlexFolland** [comment] 2024-02-16 19:42
Thank you for the report!  This is a known issue with AutoGear in Dragonflight 10.0.2 and later, as AutoGear is only compatible with Dragonflight 10.0.0.  I have purposely not updated the TOC version number for Dragonflight 10.0.2, since my attempts to resolve the issues after Blizzard's extreme and limiting API changes were met with a ton of difficulty.

Since several people have reported this since the release of Dragonflight 10.0.2, this ticket is a duplicate of the first report of this issue, and I'll "close as not planned" because that's what GitHub says to use if a ticket is a duplicate, even though I don't consider resolving this to be "not planned".  I appreciate your report nonetheless.  Here's the original report ticket: https://github.com/AlexFolland/AutoGear/issues/38

By the way, that original report ticket has a comment with an update from me about the status of AutoGear from my perspective, including information about my attempt to fix AutoGear with the API changes introduced by Dragonflight version 10.0.2.  Here's a direct link to that comment: https://github.com/AlexFolland/AutoGear/issues/38#issuecomment-1949172287  If you are interested in the status of AutoGear, please read that comment.

Thank you for your interest!

**Closed by AlexFolland** 2024-02-16 19:42 UTC
