### ISSUE TITLE
Error on Party Join

### ISSUE THREAD

**Issue by TranceKat1200** [AlexFolland/AutoGear#4] opened 2019-09-16 11:59 UTC
Here's the error that occurs on party join in WoW Classic:

Date: 2019-09-16 07:53:37
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AutoGear\AutoGear.lua line 273:
   Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
Debug:
   [C]: ?
   [C]: RegisterEvent()
   AutoGear\AutoGear.lua:273:
      AutoGear\AutoGear.lua:196
Locals:

AddOns:
...lots of addons...
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=8e2)

**Comment by AlexFolland** [comment] 2019-09-16 12:13
Are you sure you're running the latest version?  I can't reproduce this.

**Comment by AlexFolland** [comment] 2019-09-19 04:19
Synthetikaryote reproduced this.  I think I just pushed a fix.  Feel free to close this if it's fixed now.  Thanks!

**Comment by AlexFolland** [comment] 2019-09-23 14:39
I'm pretty sure now this is fixed.  Thanks.  Please feel free to comment if it's not.

**Closed by AlexFolland** 2019-09-23 14:39 UTC
