### ISSUE TITLE
[Druid][Classic][Quest Reward] Feral Stat Weights

### ISSUE THREAD

**Issue by Sattva-108** [AlexFolland/AutoGear#48] opened 2023-08-13 05:36 UTC
## Quest Link:
[The Fragments Within](https://www.wowhead.com/classic/quest=4813/the-fragments-within)

## Wrong reward chosen
[Dagger 1 stam](https://www.wowhead.com/classic/item=15396/curvewood-dagger)
over
[Staff 2 stam 2 int](https://www.wowhead.com/classic/item=15397/oakthrush-staff)

![firefox_kmALnzM5G2](https://github.com/AlexFolland/AutoGear/assets/74269253/46423ac4-2a85-4ef3-b1c0-ad5930ca6216)

Please tell me why. Can it be fixed?

**Comment by AlexFolland** [comment] 2023-08-13 06:20
As far as I was aware before now, AutoGear wasn't working on druids at all, as [this ticket](https://github.com/AlexFolland/AutoGear/issues/45) explains, so it's surprising to see it actually working for you.  I've done a thorough investigation in the other ticket, and the code path that is executed looks bulletproof, yet still fails, which makes absolutely no sense from my perspective, especially considering that AutoGear was working perfectly on druids when I was last playing, in 2022.

I want to resolve this bizarre behavior with druids, but to do that, I need more information about what information the game is giving to AutoGear on a druid for those particular items, and what AutoGear's item information becomes with that information.

Please do the following to give me more information, if possible.

1. Log onto this character or a similar character with the same kind of setup and specialization.  Ideally, it would be at the same character level and with the same specialization as when the quest was turned in, but I realize that may not be easy.
2. Type `/ag spec` in the chat and give me the output.
3. Enable tooltip debug mode in AutoGear's options.
4. Show me tooltips of the 2-handers and 1-handers you had in your bags and equipped at the time you turned in the quest.  This will show AutoGear debug information, which includes evaluations about the items.
5. Load item links for these quest items in-game and show me their tooltips.  This will show AutoGear debug information, which includes evaluations about the items.

Thank you very much for the report and any follow-up information you can give me.

**Comment by Sattva-108** [comment] 2023-08-17 11:48
I'm really sorry for late response. 
The guy i wanted to help is a streamer and doubt he has time to do this. 
I would do all those myself. But I don't have Blizzard game-time.

I just can say that he told me that it's fine to use your auto-equip and auto-choose reward as druid until like level 15 Night Elf. 
Then he turns those automation options off. 

Feel free to close the issue, if that doesn't help anyhow. And sorry for bothering you. 
Thank you for providing this guide to debug issue, but i cannot help myself without being able to launch game.

**Comment by AlexFolland** [comment] 2024-06-05 05:51
Thank you for this report last year.  I realize it's been almost a year.  I haven't had time to play WoW much since then, let alone program addons.

I performed a huge refactor yesterday that may have resolved this issue.  After working on the refactor yesterday, I think I have a better understanding now of how it might have happened.  I don't have a simple way to test whether this particular issue is fixed right now, so I will close this ticket now.  Please feel free to comment again asking to reopen the ticket or create a new issue ticket if you can still reproduce this issue or a similar issue.

**Closed by AlexFolland** 2024-06-05 05:51 UTC

**Comment by AlexFolland** [comment] 2024-11-27 01:35
I've updated AutoGear to work for DF and TWW.  There are 3 known issues:

- Typing `/ag` to show the options menu does something weird and doesn't show the addon options menu properly.  It shows the main settings menu instead.  I'm not sure why right now.
- Tooltips in the options menu don't show up at all, so it's hard to learn about the options right now.
- All AutoGear built-in stat weights are not updated, so just use Pawn scales for weights because AutoGear's built-in weights are either not ideal or don't work at all right now.

I plan to solve the options menu issues soon.
